import CampaignCommands as Campaign

Incursion = Campaign.Commands('IncursionSave')
Incursion.init_campaign()
Incursion.add_planet('Prillia', 500, "team 1", "team 1")
Incursion.add_planet('Orilius', 1000, "team 2", "team 2")
Incursion.add_connection('Prillia', 'Orilius', 1)
Incursion.add_player('Starficz', 'team 1')
Incursion.add_player('Owlfeathers', 'team 2')
Incursion.cheat_in_resources('Prillia', 'Starficz', 20000)
Incursion.cheat_in_resources('Orilius', 'Owlfeathers', 20000)
Incursion.add_ship_to_campaign('test ship1', 100, 200, 300)
Incursion.add_ship_to_campaign('test ship2', 200, 400, 600)
Incursion.make_ship('Prillia', 'Starficz', 'test ship1', 10)
Incursion.make_ship('Orilius', 'Owlfeathers', 'test ship2', 10)
Incursion.advance_turn()
Incursion.make_fleet('Prillia', 'Starficz', 'test fleet1', {'test ship1': 5})
Incursion.make_fleet('Orilius', 'Owlfeathers', 'test fleet2', {'test ship2': 3})
Incursion.transfer_resources('Prillia', 1000, 'Starficz', 'Prillia', 'Starficz', 'test fleet1')
Incursion.hohmann_fleet_transfer('Starficz', 'test fleet1', 'Prillia', 'Orilius')
Incursion.advance_turn()
Incursion.close_campaign()