import CampaignCommands as Campaign

Incursion = Campaign.Commands('IncursionSave')
Incursion.init_campaign()
Incursion.add_planet('Prillia', 500, "team 1", "team 1")
Incursion.add_planet('Orilius', 1000, "team 1", "team 1")
Incursion.add_connection('Prillia', 'Orilius', 1)
Incursion.add_player('Starficz', 'team 1')
Incursion.cheat_in_resources('Prillia', 'Starficz', 20000)
Incursion.add_ship_to_campaign('test ship1', 100, 200, 300)
Incursion.add_ship_to_campaign('test ship2', 200, 400, 600)
Incursion.make_ship('Prillia', 'Starficz', 'test ship1', 2)
Incursion.make_ship('Prillia', 'Starficz', 'test ship2', 10)
Incursion.cheat_in_ship('Prillia', 'Starficz', 'test ship1', 3)
Incursion.advance_turn()
Incursion.make_fleet('Prillia', 'Starficz', 'test fleet1', {'test ship1': 3, 'test ship2': 3})
Incursion.make_fleet('Prillia', 'Starficz', 'test fleet2', {'test ship1': 1, 'test ship2': 6})
Incursion.transfer_resources('Prillia', 1000, 'Starficz', 'planet', 'Starficz', 'test fleet1')
Incursion.transfer_resources('Prillia', 1000, 'Starficz', 'planet', 'Starficz', 'test fleet2')
Incursion.hohmann_fleet_transfer('Starficz', 'test fleet1', 'Prillia', 'Orilius')
Incursion.brachistochrone_fleet_transfer('Starficz', 'test fleet2', 'Prillia', 'Orilius')
Incursion.disband_fleet('Orilius', 'Starficz', 'test fleet2')
Incursion.scrap_ship('Orilius', 'Starficz', 'test ship2', 4)
Incursion.advance_turn()
Incursion.disband_fleet('Orilius', 'Starficz', 'test fleet1')
Incursion.scrap_ship('Orilius', 'Starficz', 'test ship1', 2)
help(Campaign.Commands.make_ship)
Incursion.close_campaign()