from CampaignCommands import Commands

def initalizeSave():
    Incursion = Commands('IncursionSave')
    Incursion.init_campaign()
    Incursion.add_planet('Prillia', 500, 'HDC', 'HDC')
    Incursion.add_planet('Orilius', 1000, 'HDC', 'HDC')
    Incursion.add_planet('Atov', 1200, 'HDC', 'HDC')
    Incursion.add_planet('Taides', 500, 'HDC', 'HDC')
    Incursion.add_planet('Breos', 750, 'HDC', 'HDC')
    Incursion.add_planet('Vosmet', 500, 'HDC', 'HDC')
    Incursion.add_planet('Dielka', 1250, 'HDC', 'HDC')
    Incursion.add_planet('Pryke', 600, 'HDC', 'HDC')
    Incursion.add_planet('Trapus', 250, 'HDC', 'HDC')
    Incursion.add_planet('Clauds', 250, 'HDC', 'HDC')
    Incursion.add_planet('Helcathus', 2000, 'Neutral', 'Neutral')
    Incursion.add_planet('Mallis', 750, 'Neutral', 'Neutral')
    Incursion.add_planet('Sulfas', 300, 'HDC', 'HDC')
    Incursion.add_planet('Vectal', 700, 'HDC', 'HDC')
    Incursion.add_planet('Cathaeus', 700, 'HDC', 'HDC')
    Incursion.add_planet('Voss', 300, 'HDC', 'HDC')
    Incursion.add_planet('Daitera', 500, 'HDC', 'HDC')
    Incursion.add_planet('Yoeturna', 1500, 'PC', 'PC')
    Incursion.add_planet('Palleos', 500, 'PC', 'PC')
    Incursion.add_planet('Hosnoth', 750, 'PC', 'PC')
    Incursion.add_planet('Astaeya', 1000, 'PC', 'PC')
    Incursion.add_connection('Prillia', 'Orilius', 1)
    Incursion.add_connection('Orilius', 'Atov', 4)
    Incursion.add_connection('Orilius', 'Taides', 4)
    Incursion.add_connection('Orilius', 'Breos', 2)
    Incursion.add_connection('Atov', 'Pryke', 2)
    Incursion.add_connection('Atov', 'Taides', 2)
    Incursion.add_connection('Taides', 'Pryke', 2)
    Incursion.add_connection('Taides', 'Sulfas', 6)
    Incursion.add_connection('Taides', 'Dielka', 2)
    Incursion.add_connection('Taides', 'Breos', 2)
    Incursion.add_connection('Breos', 'Dielka', 4)
    Incursion.add_connection('Breos', 'Vosmet', 1)
    Incursion.add_connection('Pryke', 'Trapus', 1)
    Incursion.add_connection('Pryke', 'Clauds', 1)
    Incursion.add_connection('Pryke', 'Cathaeus', 8)
    Incursion.add_connection('Pryke', 'Dielka', 4)
    Incursion.add_connection('Dielka', 'Sulfas', 4)
    Incursion.add_connection('Dielka', 'Helcathus', 2)
    Incursion.add_connection('Cathaeus', 'Voss', 1)
    Incursion.add_connection('Cathaeus', 'Yoeturna', 6)
    Incursion.add_connection('Cathaeus', 'Daitera', 4)
    Incursion.add_connection('Cathaeus', 'Sulfas', 2)
    Incursion.add_connection('Sulfas', 'Vectal', 1)
    Incursion.add_connection('Sulfas', 'Mallis', 2)
    Incursion.add_connection('Sulfas', 'Helcathus', 2)
    Incursion.add_connection('Helcathus', 'Mallis', 2)
    Incursion.add_connection('Mallis', 'Daitera', 4)
    Incursion.add_connection('Daitera', 'Yoeturna', 2)
    Incursion.add_connection('Yoeturna', 'Palleos', 1)
    Incursion.add_connection('Yoeturna', 'Hosnoth', 2)
    Incursion.add_connection('Hosnoth', 'Astaeya', 1)
    Incursion.add_player('Aleksander Wit', 'HDC')
    Incursion.add_player('Bolvangr', 'HDC')
    Incursion.add_player('Conga', 'HDC')
    Incursion.add_player('Husk', 'HDC')
    Incursion.add_player('NoahStrike', 'HDC')
    Incursion.add_player('Margakis', 'HDC')
    Incursion.add_player('Miditoxic', 'HDC')
    Incursion.add_player('Starficz', 'HDC')
    Incursion.add_player('Splinterman', 'HDC')
    Incursion.add_player('Zfall99', 'HDC')
    Incursion.add_player('Floof', 'PC')
    Incursion.add_player('Owlfeathers', 'PC')

if __name__ == '__main__':
    print("| Writing save file... |")
    initalizeSave()
    print("| Writing complete!... |")
